FROM java:8
WORKDIR /usr/src/app/owl2vowl
# ADD owl2vowl-rest-service-ok.jar owl2vowl-rest-service-ok.jar
COPY ./owl2vowl-rest-service-ok.jar .
EXPOSE 9090
CMD [ "java", "-jar","owl2vowl-rest-service-ok.jar"]
